spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
  kakao:
    redirect-uri: https://itcast.site/auth/kakao/callback
    client-id: ${KAKAO_CLIENT_ID}

aws:
  ses:
    access-key: ${AWS_SES_ACCESS_KEY}
    secret-key: ${AWS_SES_SECRET_KEY}
    sender-email: ${AWS_SES_SENDER_EMAIL}
  region: ap-northeast-2

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

sms:
  api:
    key: ${SMS_API_KEY}
    secret: ${SMS_API_SECRET}
  sender:
    phone: ${SMS_SENDER_PHONE}

slack:
  token: ${SLACK_TOKEN}
  channel:
    monitor: ${SLACK_CHANNEL_MONITOR}

logging:
  level:
    org:
      hibernate:
        sql: warn
        type:
          descriptor:
            sql:
              BasicBinder: warn
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
server:
  port: 8080
