spring:
  datasource:
    url: jdbc:mysql://localhost:3308/itcast
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  mail:
    host: smtp.naver.com
    port: 465
    username: ${ADMIN_MAIL}
    password: ${ADMIN_MAIL_PASSWORD}
    properties:
      auth: true
      starttlsEnable: false
      sslEnable: true

  kakao:
    redirect-uri: http://localhost:8080/auth/kakao/callback

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

server:
  port: 8082
