spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.naver.com
    port: 465
    username: ${ADMIN_MAIL}
    password: ${ADMIN_MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: false
          ssl:
            enable: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

logging:
  level:
    org:
      hibernate:
        sql: warn
        type:
          descriptor:
            sql:
              BasicBinder: warn
    root: info

server:
  port: 8082
