server:
  port: 8085
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  profiles:
    active: test
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      '[hibernate.default_batch_fetch_size]': 100
      '[hibernate.format_sql]': true
    show-sql: true
  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    com.sparta.twitNation: DEBUG
